const mongoose = require("mongoose");
const dotenv = require("dotenv");
const path = require("path");
const Sticker = require("../models/Sticker");

dotenv.config({ path: path.resolve(__dirname, "../../.env") });

const players = {
  MEX: [
    "Logo da Seleção",
    "Luis Malagón",
    "Johan Vásquez",
    "Jorge Sánchez",
    "César Montes",
    "Jesús Gallardo",
    "Israel Reyes",
    "Diego Lainez",
    "Carlos Rodríguez",
    "Edson Álvarez",
    "Orbelín Pineda",
    "Marcel Ruiz",
    "Foto Oficial da Seleção",
    "Érick Sánchez",
    "Hirving Lozano",
    "Santiago Giménez",
    "Raúl Jiménez",
    "Alexis Vega",
    "Roberto Alvarado",
    "César Huerta",
  ],
  RSA: [
    "Logo da Seleção",
    "Ronwen Williams",
    "Sipho Chaine",
    "Aubrey Modiba",
    "Samukele Kabini",
    "Mbekezeli Mbokazi",
    "Khulumani Ndamane",
    "Siyabonga Ngezana",
    "Khuliso Mudau",
    "Nkosinathi Sibisi",
    "Teboho Mokoena",
    "Thalente Mbatha",
    "Foto Oficial da Seleção",
    "Bathuisi Aubaas",
    "Yaya Sithole",
    "Sipho Mbule",
    "Lyle Foster",
    "Ioraam Rayners",
    "Mohau Nkota",
    "Oswin Appolis",
  ],
  KOR: [
    "Logo da Seleção",
    "Hyeon-woo Jo",
    "Seung-Gyu Kim",
    "Min-jae Kim",
    "Yu-min Cho",
    "Young-woo Seol",
    "Han-beom Lee",
    "Tae-seok Lee",
    "Myung-jae Lee",
    "Jae-sung Lee",
    "In-beom Hwang",
    "Kang-in Lee",
    "Foto Oficial da Seleção",
    "Seung-ho Paik",
    "Jens Castrop",
    "Dong-gyeong Lee",
    "Gue-sung Cho",
    "Heung-min Son",
    "Hee-chan Hwang",
    "Hyeon-Gyu Oh",
  ],
  CZE: [
    "Logo da Seleção",
    "Matěj Kovář",
    "Jindřich Staněk",
    "Ladislav Krejčí",
    "Vladimír Coufal",
    "Jaroslav Zelený",
    "Tomáš Holeš",
    "David Zima",
    "Michal Sadílek",
    "Lukáš Provod",
    "Lukáš Červ",
    "Tomáš Souček",
    "Foto Oficial da Seleção",
    "Pavel Šulc",
    "Matěj Vydra",
    "Vasil Kušej",
    "Tomáš Chorý",
    "Václav Černý",
    "Adam Hložek",
    "Patrik Schick",
  ],
  CAN: [
    "Logo da Seleção",
    "Dayne St. Clair",
    "Alphonso Davies",
    "Alistair Johnston",
    "Samuel Adekugbe",
    "Richie Laryea",
    "Derek Cornelius",
    "Moïse Bombito",
    "Kamal Miller",
    "Stephen Eustáquio",
    "Ismaël Koné",
    "Jonathan Osorio",
    "Foto Oficial da Seleção",
    "Jacob Shaffelburg",
    "Mathieu Choinière",
    "Niko Sigur",
    "Tajon Buchanan",
    "Liam Millar",
    "Cyle Larin",
    "Jonathan David",
  ],
  BIH: [
    "Logo da Seleção",
    "Nikola Vasilj",
    "Amar Dedić",
    "Sead Kolašinac",
    "Tarik Muharemović",
    "Nihad Mujakić",
    "Nikola Katić",
    "Amir Hadžiahmetović",
    "Benjamin Tahirović",
    "Armin Gigović",
    "Ivan Šunjić",
    "Ivan Bašić",
    "Foto Oficial da Seleção",
    "Dženis Burnić",
    "Esmir Bajraktarević",
    "Amar Memić",
    "Ermedin Demirović",
    "Edin Džeko",
    "Samed Baždar",
    "Haris Tabaković",
  ],
  QAT: [
    "Logo da Seleção",
    "Meshaal Barsham",
    "Sultan Albrake",
    "Lucas Mendes",
    "Homam Ahmed",
    "Boualem Khoukhi",
    "Pedro Miguel",
    "Tarek Salman",
    "Mohamed Al-Mannai",
    "Karim Boudiaf",
    "Assim Madibo",
    "Ahmed Fatehi",
    "Foto Oficial da Seleção",
    "Mohammed Waad",
    "Abdulaziz Hatem",
    "Hassan Al-Haydos",
    "Edmilson Junior",
    "Akram Hassan Afif",
    "Ahmed Al Ganehi",
    "Almoez Ali",
  ],
  SUI: [
    "Logo da Seleção",
    "Gregor Kobel",
    "Yvon Mvogo",
    "Manuel Akanji",
    "Ricardo Rodriguez",
    "Nico Elvedi",
    "Aurèle Amenda",
    "Silvan Widmer",
    "Granit Xhaka",
    "Denis Zakaria",
    "Remo Freuler",
    "Fabian Rieder",
    "Foto Oficial da Seleção",
    "Ardon Jashari",
    "Johan Manzambi",
    "Michel Aebischer",
    "Breel Embolo",
    "Ruben Vargas",
    "Dan Ndoye",
    "Zeki Amdouni",
  ],
  BRA: [
    "Logo da Seleção",
    "Alisson",
    "Bento",
    "Marquinhos",
    "Éder Militão",
    "Gabriel Magalhães",
    "Danilo",
    "Wesley",
    "Lucas Paquetá",
    "Casemiro",
    "Bruno Guimarães",
    "Luiz Henrique",
    "Foto Oficial da Seleção",
    "Vinícius Júnior",
    "Rodrygo",
    "João Pedro",
    "Matheus Cunha",
    "Gabriel Martinelli",
    "Raphinha",
    "Estêvão",
  ],
  MAR: [
    "Logo da Seleção",
    "Yassine Bounou",
    "Munir El Kajoui",
    "Achraf Hakimi",
    "Noussair Mazraoui",
    "Nayef Aguerd",
    "Romain Saïss",
    "Jawad El Yamiq",
    "Adam Masina",
    "Sofyan Amrabat",
    "Azzedine Ounahi",
    "Eliesse Ben Seghir",
    "Foto Oficial da Seleção",
    "Bilal El Khannouss",
    "Ismael Saibari",
    "Youssef En-Nesyri",
    "Abde Ezzalzouli",
    "Soufiane Rahimi",
    "Brahim Díaz",
    "Ayoub El Kaabi",
  ],
  HAI: [
    "Logo da Seleção",
    "Johny Placide",
    "Carlens Arcus",
    "Martin Expérience",
    "Jean-Kevin Duverne",
    "Ricardo Adé",
    "Duke Lacroix",
    "Garven Metusala",
    "Hannes Delcroix",
    "Leverton Pierre",
    "Danley Jean Jacques",
    "Jean-Ricner Bellegarde",
    "Foto Oficial da Seleção",
    "Christopher Attys",
    "Derrick Etienne Jr.",
    "Josué Casimir",
    "Ruben Providence",
    "Duckens Nazon",
    "Louicius Deedson",
    "Frantzdy Pierrot",
  ],
  SCO: [
    "Logo da Seleção",
    "Angus Gunn",
    "Jack Hendry",
    "Kieran Tierney",
    "Aaron Hickey",
    "Andrew Robertson",
    "Scott McKenna",
    "John Souttar",
    "Anthony Ralston",
    "Grant Hanley",
    "Scott McTominay",
    "Billy Gilmour",
    "Foto Oficial da Seleção",
    "Lewis Ferguson",
    "Ryan Christie",
    "Kenny McLean",
    "John McGinn",
    "Lyndon Dykes",
    "Che Adams",
    "Ben Gannon-Doak",
  ],
  USA: [
    "Logo da Seleção",
    "Math Freese",
    "Chris Richards",
    "Tim Ream",
    "Mark McKenzie",
    "Alex Freeman",
    "Antonee Robinson",
    "Tyler Adams",
    "Tanner Tessmann",
    "Weston McKenny",
    "Christian Roldan",
    "Timothy Weah",
    "Foto Oficial da Seleção",
    "Diego Luna",
    "Malik Tillman",
    "Christian Pulisic",
    "Brenden Aaronson",
    "Ricardo Pepi",
    "Haji Wright",
    "Folarin Balogun",
  ],
  PAR: [
    "Logo da Seleção",
    "Roberto Fernández",
    "Orlando Gill",
    "Gustavo Gómez",
    "Fabián Balbuena",
    "Juan José Cáceres",
    "Omar Alderete",
    "Júnior Alonso",
    "Mathías Villasanti",
    "Diego Gómez",
    "Damián Bobadilla",
    "Andrés Cubas",
    "Foto Oficial da Seleção",
    "Matías Galarza Fonda",
    "Julio Enciso",
    "Alejandro Romero Gamarra",
    "Miguel Almirón",
    "Ramón Sosa",
    "Ángel Romero",
    "Antonio Sanabria",
  ],
  AUS: [
    "Logo da Seleção",
    "Mathew Ryan",
    "Joe Gauci",
    "Harry Souttar",
    "Alessandro Circati",
    "Jordan Bos",
    "Aziz Behich",
    "Cameron Burgess",
    "Lewis Miller",
    "Milos Degenek",
    "Jackson Irvine",
    "Riley McGree",
    "Foto Oficial da Seleção",
    "Aiden O'Neill",
    "Connor Metcalfe",
    "Patrick Yazbek",
    "Craig Goodwin",
    "Kusini Yengi",
    "Nestory Irankunda",
    "Mohamed Touré",
  ],
  TUR: [
    "Logo da Seleção",
    "Ugurcan Cakir",
    "Mert Muldur",
    "Zeki Celik",
    "Abdulkerim Bardakci",
    "Caglar Soyunku",
    "Merih Demiral",
    "Ferdi Kadioglu",
    "Kaan Ayhan",
    "Ismail Yuksek",
    "Hakan Calhanoglu",
    "Orkun Kokcu",
    "Foto Oficial da Seleção",
    "Arda Güler",
    "Irfan Can Kahveci",
    "Yunus Akgun",
    "Can Uzun",
    "Baris Alper Yilmaz",
    "Kerem Akturkoglu",
    "Kenan Yildiz",
  ],
  GER: [
    "Logo da Seleção",
    "Marc-André ter Stegen",
    "Jonathan Tah",
    "David Raum",
    "Nico Schlotterbeck",
    "Antonio Rüdiger",
    "Waldemar Anton",
    "Ridle Baku",
    "Maximilian Mittelstädt",
    "Joshua Kimmich",
    "Florian Wirtz",
    "Felix Nmecha",
    "Foto Oficial da Seleção",
    "Leon Goretzka",
    "Jamal Musiala",
    "Serge Gnabry",
    "Kai Havertz",
    "Leroy Sané",
    "Karim Adeyemi",
    "Nick Woltemade",
  ],
  CUW: [
    "Logo da Seleção",
    "Eloy Room",
    "Armando Obispo",
    "Sherel Floranus",
    "Jurien Gaari",
    "Joshua Brenet",
    "Roshon Van Eijma",
    "Shurandy Sambo",
    "Livano Comenencia",
    "Godfried Roemeratoe",
    "Juninho Bacuna",
    "Leandro Bacuna",
    "Foto Oficial da Seleção",
    "Tahith Chong",
    "Kenji Gorré",
    "Jearl Margaritha",
    "Jurgen Locadia",
    "Jeremy Antonisse",
    "Gervane Kastaneer",
    "Sontje Hansen",
  ],
  CIV: [
    "Logo da Seleção",
    "Yahia Fofana",
    "Ghislain Konan",
    "Wilfried Singo",
    "Odilon Kossounou",
    "Evan Ndicka",
    "Willy Boly",
    "Emmanuel Agbadou",
    "Ousmane Diomande",
    "Franck Kessié",
    "Seko Fofana",
    "Ibrahim Sangaré",
    "Foto Oficial da Seleção",
    "Jean-Philippe Gbamin",
    "Amad Diallo",
    "Sébastien Haller",
    "Simon Adingra",
    "Yan Diomande",
    "Evann Guessand",
    "Oumar Diakité",
  ],
  ECU: [
    "Logo da Seleção",
    "Hernán Galíndez",
    "Gonzalo Valle",
    "Piero Hincapié",
    "Pervis Estupiñán",
    "Willian Pacho",
    "Ángelo Preciado",
    "Joel Ordóñez",
    "Moisés Caicedo",
    "Alan Franco",
    "Kendry Páez",
    "Pedro Vite",
    "Foto Oficial da Seleção",
    "John Veboah",
    "Leonardo Campana",
    "Gonzalo Plata",
    "Nilson Angulo",
    "Alan Minda",
    "Kevin Rodríguez",
    "Enner Valencia",
  ],
  NED: [
    "Logo da Seleção",
    "Bart Verbruggen",
    "Virgil van Dijk",
    "Micky van de Ven",
    "Jurriën Timber",
    "Denzel Dumfries",
    "Nathan Aké",
    "Jeremie Frimpong",
    "Jan Paul van Hecke",
    "Tijjani Reijnders",
    "Ryan Gravenberch",
    "Teun Koopmeiners",
    "Foto Oficial da Seleção",
    "Frenkie de Jong",
    "Xavi Simons",
    "Justin Kluivert",
    "Memphis Depay",
    "Donyell Malen",
    "Wout Weghorst",
    "Cody Gakpo",
  ],
  JPN: [
    "Logo da Seleção",
    "Zion Suzuki",
    "Henry Heroki Mochizuki",
    "Ayumu Seko",
    "Junnosuke Suzuki",
    "Shogo Taniguchi",
    "Tsuyoshi Watanabe",
    "Kaishu Sano",
    "Yuki Soma",
    "Ao Tanaka",
    "Daichi Kamada",
    "Takefusa Kubo",
    "Foto Oficial da Seleção",
    "Ritsu Doan",
    "Keito Nakamura",
    "Takumi Minamino",
    "Shuto Machino",
    "Junya Ito",
    "Koki Ogawa",
    "Ayase Ueda",
  ],
  SWE: [
    "Logo da Seleção",
    "Victor Johansson",
    "Isak Hien",
    "Gabriel Gudmundsson",
    "Emil Holm",
    "Victor Nilsson Lindelöf",
    "Gustaf Lagerbielke",
    "Lucas Bergvall",
    "Hugo Larsson",
    "Jesper Karlström",
    "Yasin Ayari",
    "Mattias Svanberg",
    "Foto Oficial da Seleção",
    "Daniel Svensson",
    "Ken Sema",
    "Roony Bardghji",
    "Dejan Kulusevski",
    "Anthony Elanga",
    "Alexander Isak",
    "Viktor Gyökeres",
  ],
  TUN: [
    "Logo da Seleção",
    "Bechir Ben Said",
    "Aymen Dahmen",
    "Van Valery",
    "Montassar Talbi",
    "Yassine Meriah",
    "Ali Abdi",
    "Dylan Bronn",
    "Ellyes Skhiri",
    "Aissa Laidouni",
    "Ferjani Sassi",
    "Mohamed Ali Ben Romdhane",
    "Foto Oficial da Seleção",
    "Hannibal Mejbri",
    "Elias Achouri",
    "Elias Saad",
    "Hazem Mastouri",
    "Ismael Gharbi",
    "Sayfallah Ltaief",
    "Naim Sliti",
  ],
  BEL: [
    "Logo da Seleção",
    "Thibaut Courtois",
    "Arthur Theate",
    "Timothy Castagne",
    "Zeno Debast",
    "Brandon Mechele",
    "Maxim De Cuyper",
    "Thomas Meunier",
    "Youri Tielemans",
    "Amadou Onana",
    "Nicolas Raskin",
    "Alexis Saelemaekers",
    "Foto Oficial da Seleção",
    "Hans Vanaken",
    "Kevin De Bruyne",
    "Jérémy Doku",
    "Charles De Ketelaere",
    "Leandro Trossard",
    "Loïs Openda",
    "Romelu Lukaku",
  ],
  EGY: [
    "Logo da Seleção",
    "Mohamed El Shenawy",
    "Mohamed Hany",
    "Mohamed Hamdy",
    "Yasser Ibrahim",
    "Khaled Sobhi",
    "Ramy Rabia",
    "Hossam Abdelmaguid",
    "Ahmed Fatouh",
    "Marwan Attia",
    "Zizo",
    "Hamdy Fathy",
    "Foto Oficial da Seleção",
    "Mohamed Lasheen",
    "Emam Ashour",
    "Osama Faisal",
    "Mohamed Salah",
    "Mostafa Mohamed",
    "Trezeguet",
    "Omar Marmoush",
  ],
  IRN: [
    "Logo da Seleção",
    "Alireza Beiranvand",
    "Morteza Pouraliganji",
    "Ehsan Hajsafi",
    "Milad Mohammadi",
    "Shojae Khalilzadeh",
    "Ramin Rezaeian",
    "Hossein Kanaani",
    "Sadegh Moharrami",
    "Saleh Hardani",
    "Saeed Ezatolahi",
    "Saman Ghoddos",
    "Foto Oficial da Seleção",
    "Omid Noorafkan",
    "Roozbeh Cheshmi",
    "Mohammad Mohebi",
    "Sardar Azmoun",
    "Mehdi Taremi",
    "Alireza Jahanbakhsh",
    "Ali Gholizadeh",
  ],
  NZL: [
    "Logo da Seleção",
    "Max Crocombe-Payne",
    "Alex Paulsen",
    "Michael Boxall",
    "Liberato Cacace",
    "Tim Payne",
    "Tyler Bindon",
    "Francis de Vries",
    "Finn Surman",
    "Joe Bell",
    "Sarpreet Singh",
    "Ryan Thomas",
    "Foto Oficial da Seleção",
    "Matthew Garbett",
    "Marko Stamenić",
    "Ben Old",
    "Chris Wood",
    "Elijah Just",
    "Callum McCowatt",
    "Kosta Barbarouses",
  ],
  ESP: [
    "Logo da Seleção",
    "Unai Simón",
    "Robin Le Normand",
    "Aymeric Laporte",
    "Dean Huijsen",
    "Pedro Porro",
    "Dani Carvajal",
    "Marc Cucurella",
    "Martín Zubimendi",
    "Rodri",
    "Pedri",
    "Fabián Ruiz",
    "Foto Oficial da Seleção",
    "Mikel Merino",
    "Lamine Yamal",
    "Dani Olmo",
    "Nico Williams",
    "Ferran Torres",
    "Álvaro Morata",
    "Mikel Oyarzabal",
  ],
  CPV: [
    "Logo da Seleção",
    "Vozinha",
    "Logan Costa",
    "Pico",
    "Diney",
    "Steven Moreira",
    "Wagner Pina",
    "João Paulo",
    "Yannick Semedo",
    "Kevin Pina",
    "Patrick Andrade",
    "Jamiro Monteiro",
    "Foto Oficial da Seleção",
    "Deroy Duarte",
    "Garry Rodrigues",
    "Jovane Cabral",
    "Ryan Mendes",
    "Dailon Livramento",
    "Willy Semedo",
    "Bebé",
  ],
  KSA: [
    "Logo da Seleção",
    "Nawaf Alaqidi",
    "Abdulrahman Al-Sanbi",
    "Saud Abdulhamid",
    "Nawaf Buwashl",
    "Jehad Thikri",
    "Moteb Al-Harbi",
    "Hassan Altambakti",
    "Musab Aljuwayr",
    "Ziyad Aljohani",
    "Abdullah Alkhaibari",
    "Nasser Aldawsari",
    "Foto Oficial da Seleção",
    "Saleh Abu Alshamat",
    "Marwan Alsahafi",
    "Salem Aldawsari",
    "Abdulrahman Al-Alobud",
    "Feras Albrikan",
    "Saleh Alshehri",
    "Abdullah Al-Hamdan",
  ],
  URU: [
    "Logo da Seleção",
    "Sergio Rochet",
    "Santiago Mele",
    "Ronald Araújo",
    "José María Giménez",
    "Sebastián Cáceres",
    "Mathías Olivera",
    "Guillermo Varela",
    "Nahitan Nández",
    "Federico Valverde",
    "Giorgian De Arrascaeta",
    "Rodrigo Bentancur",
    "Foto Oficial da Seleção",
    "Manuel Ugarte",
    "Nicolás de la Cruz",
    "Maxi Araújo",
    "Darwin Núñez",
    "Federico Viñas",
    "Rodrigo Aguirre",
    "Facundo Pellistri",
  ],
  FRA: [
    "Logo da Seleção",
    "Mike Maignan",
    "Théo Hernández",
    "William Saliba",
    "Jules Koundé",
    "Ibrahima Konaté",
    "Dayot Upamecano",
    "Lucas Digne",
    "Aurélien Tchouaméni",
    "Eduardo Camavinga",
    "Manu Koné",
    "Adrien Rabiot",
    "Foto Oficial da Seleção",
    "Michael Olise",
    "Ousmane Dembélé",
    "Bradley Barcola",
    "Désiré Doué",
    "Kingsley Coman",
    "Hugo Ekitiké",
    "Kylian Mbappé",
  ],
  SEN: [
    "Logo da Seleção",
    "Édouard Mendy",
    "Yehvann Diouf",
    "Moussa Niakhaté",
    "Abdoulaye Seck",
    "Ismail Jakobs",
    "El Hadji Malick Diouf",
    "Kalidou Koulibaly",
    "Idrissa Gana Gueye",
    "Pape Matar Sarr",
    "Pape Gueye",
    "Habib Diarra",
    "Foto Oficial da Seleção",
    "Lamine Camara",
    "Sadio Mané",
    "Ismaïla Sarr",
    "Boulaye Dia",
    "Iliman Ndiaye",
    "Nicolas Jackson",
    "Krépin Diatta",
  ],
  IRQ: [
    "Logo da Seleção",
    "Jalal Hassan",
    "Rebin Sulaka",
    "Hussein Ali",
    "Akam Hashem",
    "Merchas Doski",
    "Zaid Tahseen",
    "Manaf Younis",
    "Zidane Iqbal",
    "Amir Al-Ammari",
    "Ibrahim Bayesh",
    "Ali Jasim",
    "Foto Oficial da Seleção",
    "Youssef Amyn",
    "Aimar Sher",
    "Marko Farji",
    "Osama Rashid",
    "Ali Al-Hamadi",
    "Aymen Hussein",
    "Mohanad Ali",
  ],
  NOR: [
    "Logo da Seleção",
    "Ørjan Nyland",
    "Julian Ryerson",
    "Leo Østigård",
    "Kristoffer Vassbakk Ajer",
    "Marcus Holmgren Pedersen",
    "David Møller Wolfe",
    "Torbjørn Heggem",
    "Morten Thorsby",
    "Martin Ødegaard",
    "Sander Berge",
    "Andreas Schjelderup",
    "Foto Oficial da Seleção",
    "Patrick Berg",
    "Erling Haaland",
    "Alexander Sørloth",
    "Aron Dønnum",
    "Jørgen Strand Larsen",
    "Antonio Nusa",
    "Oscar Bobb",
  ],
  ARG: [
    "Logo da Seleção",
    "Emiliano Martínez",
    "Nahuel Molina",
    "Cristian Romero",
    "Nicolás Otamendi",
    "Nicolás Tagliafico",
    "Leonardo Balerdi",
    "Enzo Fernández",
    "Alexis Mac Allister",
    "Rodrigo De Paul",
    "Exequiel Palacios",
    "Leandro Paredes",
    "Foto Oficial da Seleção",
    "Nico Paz",
    "Franco Mastantuono",
    "Nico González",
    "Lionel Messi",
    "Lautaro Martínez",
    "Julián Alvarez",
    "Giuliano Simeone",
  ],
  ALG: [
    "Logo da Seleção",
    "Alexis Guendouz",
    "Ramy Bensebaini",
    "Youcef Atal",
    "Rayan Aït-Nouri",
    "Mohamed Amine Tougai",
    "Aïssa Mandi",
    "Ismaël Bennacer",
    "Houssem Aouar",
    "Hicham Boudaoui",
    "Ramiz Zerrouki",
    "Nabil Bentaleb",
    "Foto Oficial da Seleção",
    "Farès Chaïbi",
    "Riyad Mahrez",
    "Saïd Benrahma",
    "Anis Hadj Moussa",
    "Amine Gouiri",
    "Baghdad Bounedjah",
    "Mohammed Amoura",
  ],
  AUT: [
    "Logo da Seleção",
    "Alexander Schlager",
    "Patrick Pentz",
    "David Alaba",
    "Kevin Danso",
    "Philipp Lienhart",
    "Stefan Posch",
    "Philipp Mwene",
    "Alexander Prass",
    "Xaver Schlager",
    "Marcel Sabitzer",
    "Konrad Laimer",
    "Foto Oficial da Seleção",
    "Florian Grillitsch",
    "Nicolas Seiwald",
    "Romano Schmid",
    "Patrick Wimmer",
    "Christoph Baumgartner",
    "Michael Gregoritsch",
    "Marko Arnautovic",
  ],
  JOR: [
    "Logo da Seleção",
    "Yazeed Abulaila",
    "Ihsan Haddad",
    "Mohammad Abu Hashish",
    "Yazan Al-Arab",
    "Abdallah Nasib",
    "Saleem Obaid",
    "Mohammad Abualnadi",
    "Ibrahim Saadeh",
    "Nizar Al-Rashdan",
    "Noor Al-Rawabdeh",
    "Mohannad Abu Taha",
    "Foto Oficial da Seleção",
    "Amer Jamous",
    "Mousa Al-Taamari",
    "Yazan Al-Naimat",
    "Mahmoud Al-Mardi",
    "Ali Olwan",
    "Mohammad Abu Zrayq",
    "Ibrahim Sabra",
  ],
  POR: [
    "Logo da Seleção",
    "Diogo Costa",
    "José Sá",
    "Rúben Dias",
    "João Cancelo",
    "Diogo Dalot",
    "Nuno Mendes",
    "Gonçalo Inácio",
    "Bernardo Silva",
    "Bruno Fernandes",
    "Rúben Neves",
    "Vitinha",
    "Foto Oficial da Seleção",
    "João Neves",
    "Cristiano Ronaldo",
    "Francisco Trincão",
    "João Félix",
    "Gonçalo Ramos",
    "Pedro Neto",
    "Rafael Leão",
  ],
  COD: [
    "Logo da Seleção",
    "Lionel Mpasi",
    "Aaron Wan-Bissaka",
    "Axel Tuanzebe",
    "Arthur Masuaku",
    "Chancel Mbemba",
    "Joris Kayembe",
    "Charles Pickel",
    "Ngal'Ayel Mukau",
    "Edo Kayembe",
    "Samuel Moutoussamy",
    "Noah Sadiki",
    "Foto Oficial da Seleção",
    "Théo Bongonda",
    "Meschack Elia",
    "Yoane Wissa",
    "Brian Cipenga",
    "Fiston Mayele",
    "Cédric Bakambu",
    "Nathanaël Mbuku",
  ],
  UZB: [
    "Logo da Seleção",
    "Utkir Yusupov",
    "Farrukh Sayfiev",
    "Sherzod Nasrullaev",
    "Umar Eshmurodov",
    "Husniddin Aliqulov",
    "Rustam Ashurmatov",
    "Khojiakbar Alijonov",
    "Abdukodir Khusanov",
    "Odiljon Hamrobekov",
    "Otabek Shukurov",
    "Jamshid Iskanderov",
    "Foto Oficial da Seleção",
    "Azizbek Turgunboev",
    "Khojimat Erkinov",
    "Eldor Shomurodov",
    "Oston Urunov",
    "Jaloliddin Masharipov",
    "Igor Sergeev",
    "Abbosbek Fayzullayev",
  ],
  COL: [
    "Logo da Seleção",
    "Camilo Vargas",
    "David Ospina",
    "Dávinson Sánchez",
    "Yerry Mina",
    "Daniel Muñoz",
    "Johan Mojica",
    "Jhon Lucumí",
    "Santiago Arias",
    "Jefferson Lerma",
    "Kevin Castaño",
    "Richard Ríos",
    "Foto Oficial da Seleção",
    "James Rodríguez",
    "Juan Fernando Quintero",
    "Jorge Carrascal",
    "Jhon Arias",
    "Jhon Córdoba",
    "Luis Suárez",
    "Luis Díaz",
  ],
  ENG: [
    "Logo da Seleção",
    "Jordan Pickford",
    "John Stones",
    "Marc Guéhi",
    "Ezri Konsa",
    "Trent Alexander-Arnold",
    "Reece James",
    "Dan Burn",
    "Jordan Henderson",
    "Declan Rice",
    "Jude Bellingham",
    "Cole Palmer",
    "Foto Oficial da Seleção",
    "Morgan Rogers",
    "Anthony Gordon",
    "Phil Foden",
    "Bukayo Saka",
    "Harry Kane",
    "Marcus Rashford",
    "Ollie Watkins",
  ],
  CRO: [
    "Logo da Seleção",
    "Dominik Livaković",
    "Duje Caleta-Car",
    "Joško Gvardiol",
    "Josip Stanišić",
    "Luka Vušković",
    "Josip Šutalo",
    "Kristijan Jakić",
    "Luka Modrić",
    "Mateo Kovačić",
    "Martin Baturina",
    "Lovro Majer",
    "Foto Oficial da Seleção",
    "Mario Pašalić",
    "Petar Sučić",
    "Ivan Perišić",
    "Marco Pašalić",
    "Ante Budimir",
    "Andrej Kramarić",
    "Franjo Ivanović",
  ],
  GHA: [
    "Logo da Seleção",
    "Lawrence Ati-Zigi",
    "Tariq Lamptey",
    "Mohammed Salisu",
    "Alidu Seidu",
    "Alexander Djiku",
    "Gideon Mensah",
    "Caleb Yirenkyi",
    "Abdul Issahaku Fatawu",
    "Thomas Partey",
    "Salis Abdul Samed",
    "Kamaldeen Sulemana",
    "Foto Oficial da Seleção",
    "Mohammed Kudus",
    "Inaki Williams",
    "Jordan Ayew",
    "André Ayew",
    "Joseph Paintsil",
    "Osman Bukari",
    "Antoine Semenyo",
  ],
  PAN: [
    "Logo da Seleção",
    "Orlando Mosquera",
    "Luis Mejía",
    "Fidel Escobar",
    "Andrés Andrade",
    "Michael Amir Murillo",
    "Eric Davis",
    "José Córdoba",
    "César Blackman",
    "Cristian Martínez",
    "Aníbal Godoy",
    "Adalberto Carrasquilla",
    "Foto Oficial da Seleção",
    "Édgar Bárcenas",
    "Carlos Harvey",
    "Ismael Díaz",
    "José Fajardo",
    "Cecilio Waterman",
    "José Luis Rodríguez",
    "Alberto Quintero",
  ],
};

async function addPlayerNames() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ Conectado ao MongoDB");

    let updated = 0;

    for (const [teamCode, playerNames] of Object.entries(players)) {
      for (let i = 0; i < playerNames.length; i++) {
        const number = i + 1;
        const result = await Sticker.updateOne(
          { teamCode, number },
          { $set: { description: playerNames[i] } },
        );
        if (result.modifiedCount > 0) updated++;
      }
      console.log(`✅ ${teamCode}: nomes atualizados`);
    }

    console.log(
      `\n✅ ${updated} figurinhas atualizadas com nomes de jogadores!`,
    );
    await mongoose.disconnect();
    console.log("🔌 Desconectado do MongoDB");
    process.exit(0);
  } catch (err) {
    console.error("❌ Erro:", err.message);
    process.exit(1);
  }
}

addPlayerNames();
